# -*- coding: utf-8 -*-
"""NLP_Based_Agentic_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12BG-0z8VPcTA030iZJVm8bK3h4bSmLUq

# **Overview**
**Project Description**

This project implements an NLP-based Agentic AI system using Amazon customer reviews. The system performs two NLP tasks: Sentiment Analysis and Text Summarization using pre-trained Transformer models from Hugging Face.

An Agentic AI architecture is designed with four components: Perception, Planning, Memory, and Action. The agent receives a review, analyzes its content, decides which NLP tools are needed, and generates the appropriate output automatically.

The system demonstrates autonomous decision-making by dynamically selecting sentiment analysis, summarization, or both depending on the input review. Model performance is evaluated using Accuracy and F1-Score metrics.

# **Installing Libraries**
"""

!pip install pandas transformers torch scikit-learn sentencepiece

"""# **Loading CSV Dataset**"""

import pandas as pd

df = pd.read_csv("amazon_reviews.csv")

print("Total rows:", len(df))
df.head()

"""# **Checking Column Names**"""

print(df.columns)

"""# **Extracting Reviews & Labels**"""

reviews = df["reviewText"].astype(str).tolist()
ratings = df["overall"].tolist()

labels = []
for r in ratings:
    if r >= 4:
        labels.append("positive")
    elif r <= 2:
        labels.append("negative")
    else:
        labels.append("neutral")

print("Sample review:", reviews[0])
print("Label:", labels[0])

"""# ***If needed:***
# **!pip install transformers==4.41.2**
"""

!pip uninstall -y transformers
!pip install transformers==4.41.2

"""# **Loading NLP Models**"""

from transformers import pipeline

sentiment_model = pipeline("sentiment-analysis")
summarizer = pipeline("summarization")

"""# **NLP Tools**"""

def analyze_sentiment(text):
    result = sentiment_model(text[:512])[0]
    return result["label"], result["score"]

def summarize_text(text):
    summary = summarizer(text[:1000], max_length=60, min_length=25, do_sample=False)
    return summary[0]["summary_text"]

"""# **Agentic AI System**"""

class AgenticAI:
    def __init__(self):
        self.memory = {}

    def perceive(self, user_input):
        return user_input.lower()

    def plan(self, text):
        actions = []
        if len(text.split()) > 15:
            actions.append("summarize")
        if "good" in text or "bad" in text or "great" in text or "poor" in text:
            actions.append("sentiment")
        return actions

    def act(self, text, actions):
        results = {}

        if "sentiment" in actions:
            label, score = analyze_sentiment(text)
            results["sentiment"] = label

        if "summarize" in actions:
            results["summary"] = summarize_text(text)

        self.memory = results
        return results

    def run(self, user_input):
        perceived = self.perceive(user_input)
        actions = self.plan(perceived)
        results = self.act(user_input, actions)
        return results

"""# **Running Agent on Real Review**"""

agent = AgenticAI()

sample_review = reviews[10]
print("Review:")
print(sample_review)

print("\nAgent Output:")
print(agent.run(sample_review))

"""# **Evaluating Sentiment Model**"""

from sklearn.metrics import accuracy_score, f1_score

true = []
pred = []

for i in range(50):
    text = reviews[i]
    label = labels[i]

    prediction = sentiment_model(text[:512])[0]["label"]

    if prediction == "POSITIVE":
        pred.append("positive")
    else:
        pred.append("negative")

    true.append(label)

accuracy = accuracy_score(true, pred)
f1 = f1_score(true, pred, average="weighted")

print("Accuracy:", accuracy)
print("F1 Score:", f1)

"""# **Showing Multiple Agent Interactions**"""

for i in range(3):
    print("\nReview", i+1)
    print(reviews[i])
    print("Agent:", agent.run(reviews[i]))